### ISSUE TITLE
TODO ScatterPlot widgets

### ISSUE THREAD

**Issue by glyg** [centuri-engineering/omero-utils#1]
- [x] make mouse-over display optional
- [ ] Put some margin around the ROI
- [x] Pass x, y and c columns as creation arguments
- [ ] manage docstrings (nothing is displayed right now)
- [x] add colorbar

**Comment by glyg** [comment]
The colorbar placement is buggy, but I think the pb comes from bqplot

**Comment by qztseng** [comment]
GUI showing available datasets and selecting which one the user want to compare on the plot
